version: '3.8'
services:
  db:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: api_dev
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  server:
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - db
  front:
    restart: unless-stopped
    build:
      context: ./timeManagerClient
      dockerfile: Dockerfile
    ports:
      - 80:80
volumes:
  db_data: